
package view.QLTB;

import dao.LoaiDAO;
import dao.PhongHocDAO;
import dao.ThietBiDAO;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import model.ThietBi;
import view.TBPanel;
public class ThemTB extends javax.swing.JFrame {
    private TBPanel pr;
    public ThemTB(TBPanel pr) {
        initComponents();
        setEvent();
        this.pr = pr;
        this.setLocationRelativeTo(null);
    }
    public void setEvent(){   
        jlbThem.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                String loai = (String)jcbLoai.getSelectedItem();
                String ten = jtfTen.getText();
                String phong = jtfPhong.getText().toUpperCase().trim();
                String error = "";
                if(ten.length() == 0) error+="Tên không được bỏ trống\n";
                if(phong.length() != 0 && new PhongHocDAO().getPhongHoc(phong) == null) error+="Không tìm thấy phòng học";
                if(!error.equals("")){
                    JOptionPane.showMessageDialog(jpnThemThietBi, error);
                }
                else{
                    if(new ThietBiDAO().insert(new ThietBi(null, ten, new LoaiDAO().getMaLoai(loai), phong.length()==0?null:phong, 1))){
                        JOptionPane.showMessageDialog(jpnThemThietBi, "Thêm thành công");
                        new Thread(() -> {
                            pr.timKiem();// Làm mới màn hình hiển thị hiện tại
                        }).start();
                        new Thread(() -> {
                            pr.getPr().getPhPanel().refreshTable();
                        }).start();
                    }
                    else JOptionPane.showMessageDialog(jpnThemThietBi, "Lỗi thêm thiết bị");
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                jpnThem.setBackground(new Color(227,204,255));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jpnThem.setBackground(new Color(204,204,255));
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpnThemThietBi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbLoai = new javax.swing.JComboBox<>();
        jpnThem = new javax.swing.JPanel();
        jlbThem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfPhong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm thiết bị");
        setAlwaysOnTop(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        jLabel1.setText("Tên");

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        jLabel2.setText("Loại");

        jpnThem.setBackground(new java.awt.Color(204, 204, 255));

        jlbThem.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlbThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThem.setText("Thêm");
        jlbThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnThemLayout = new javax.swing.GroupLayout(jpnThem);
        jpnThem.setLayout(jpnThemLayout);
        jpnThemLayout.setHorizontalGroup(
            jpnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThem, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThemLayout.setVerticalGroup(
            jpnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        jLabel4.setText("Phòng");

        javax.swing.GroupLayout jpnThemThietBiLayout = new javax.swing.GroupLayout(jpnThemThietBi);
        jpnThemThietBi.setLayout(jpnThemThietBiLayout);
        jpnThemThietBiLayout.setHorizontalGroup(
            jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemThietBiLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThemThietBiLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jcbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpnThemThietBiLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfPhong))
                        .addGroup(jpnThemThietBiLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addComponent(jpnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnThemThietBiLayout.setVerticalGroup(
            jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemThietBiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpnThemThietBiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jpnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        for(String x : new LoaiDAO().getTenLoai()){
            jcbLoai.addItem(x);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThemThietBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnThemThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbLoai;
    private javax.swing.JLabel jlbThem;
    private javax.swing.JPanel jpnThem;
    private javax.swing.JPanel jpnThemThietBi;
    private javax.swing.JTextField jtfPhong;
    private javax.swing.JTextField jtfTen;
    // End of variables declaration//GEN-END:variables
}
