package view.QLTB;

import view.TBPanel;
import model.ThietBi;
import dao.LoaiDAO;
import dao.PhongHocDAO;
import dao.ThietBiDAO;
import dao.TrangThaiDAO;
import javax.swing.JOptionPane;

public class XoaSuaTB extends javax.swing.JFrame {

    private TBPanel pr;
    private ThietBi tb;

    public XoaSuaTB(TBPanel root, ThietBi tb) {
        this.pr = root;
        this.tb = tb;
        initComponents();
        setLocationRelativeTo(null);
        jcbLoai.setSelectedItem(tb.getTenLoai());
        jtfMa.setText(tb.getMa());
        jtfTen.setText(tb.getTen());
        jtfPhong.setText(tb.getPhong());
        jcbTrangThai.setSelectedItem(tb.getTenTrangThai());
    }

    public void sua() {
        String ten = jtfTen.getText().trim();
        String phong = jtfPhong.getText().toUpperCase().trim();
        if (ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên");
            return;
        }
        if (ten.length() > 50) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên dưới 50 kí tự");
            return;
        }
        if (!ten.matches("^[A-Za-z0-9 \\p{L}]+$")) {
            JOptionPane.showMessageDialog(this, "Tên thiết bị chỉ bao gồm chữ cái, số và khoảng trắng");
            return;
        }
        if (phong.length() > 4) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phòng không quá 4 kí tự");
            return;
        }
        if (phong.length() != 0 && new PhongHocDAO().getPhongHoc(phong) == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy phòng");
            return;
        }
        ThietBi x = new ThietBiDAO().getThietBi(jtfMa.getText());
        if (x != null) {
            x.setTen(ten);
            x.setTenLoai(jcbLoai.getSelectedItem().toString());
            if(phong.length()==0) x.setPhong(null);
            else x.setPhong(phong);
            x.setTenTrangThai(jcbTrangThai.getSelectedItem().toString());
            if (JOptionPane.showConfirmDialog(this, "Xác nhận sửa thông tin?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (!new ThietBiDAO().update(x)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thất bại");
                } else {
                    pr.filterRows();
                    pr.getPr().getPhPanel().filterRows();
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    this.dispose();
                }
            }
        } else {
            System.out.println("Lỗi truy vấn");
        }
    }

    public void xoa() {
        int opt = JOptionPane.showConfirmDialog(this, "Xác nhận xóa", "", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            ThietBi x = new ThietBiDAO().getThietBi(jtfMa.getText());
            if (!new ThietBiDAO().delete(x)) {
                JOptionPane.showMessageDialog(this, "Không thể xóa do có phiếu mượn liên quan");
            } else {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        pr.filterRows();
                    }
                }).start();
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        pr.getPr().getPhPanel().filterRows();
                    }
                }).start();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                this.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbLoai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtfMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbTrangThai = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtfPhong = new javax.swing.JTextField();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật thiết bị");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Loại thiết bị");

        jcbLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLoaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã");

        jtfMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtfMa.setEnabled(false);

        jLabel3.setText("Tên");

        jLabel4.setText("Trạng thái");

        jLabel6.setText("Phòng");

        jbtnSua.setBackground(new java.awt.Color(204, 255, 204));
        jbtnSua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.setToolTipText("");
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jbtnXoa.setBackground(new java.awt.Color(255, 204, 204));
        jbtnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jcbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jcbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jcbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(21, 21, 21))
        );

        for(String x : new LoaiDAO().getTenLoai()){
            jcbLoai.addItem(x);
        }
        jcbTrangThai.addItem(new  TrangThaiDAO().getTenTrangThai(0));
        jcbTrangThai.addItem(new TrangThaiDAO().getTenTrangThai(1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLoaiActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        sua();
    }//GEN-LAST:event_jbtnSuaActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        xoa();
    }//GEN-LAST:event_jbtnXoaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JComboBox<String> jcbLoai;
    private javax.swing.JComboBox<String> jcbTrangThai;
    private javax.swing.JTextField jtfMa;
    private javax.swing.JTextField jtfPhong;
    private javax.swing.JTextField jtfTen;
    // End of variables declaration//GEN-END:variables
}
