package view.QLNV;

import dao.TaiKhoanDAO;
import javax.swing.JOptionPane;
import model.TaiKhoan;
import view.MainFrame;

public class DoiMatKhau extends javax.swing.JFrame {

    private final MainFrame mf;
    private final String userName;

    public DoiMatKhau(MainFrame mf, String userName) {
        initComponents();
        this.mf = mf;
        this.userName = userName;
        this.setLocationRelativeTo(null);
    }

    public void doiMatKhau() {
        String oldPass = new String(jpfMatKhauHienTai.getPassword());
        String newPass = new String(jpfMatKhauMoi.getPassword());
        String repeatPass = new String(jpfXacNhanLai.getPassword());
        if (oldPass.contains(" ") || newPass.contains(" ")) {
            JOptionPane.showMessageDialog(jPanel1, "Mật khẩu không được chứa khoảng trắng");
        } else {
            TaiKhoan tk = new TaiKhoanDAO().get(userName);
            if (!oldPass.equals(tk.getMk())) {
                JOptionPane.showMessageDialog(jPanel1, "Sai mật khẩu");
            } else if (!repeatPass.equals(newPass)) {
                JOptionPane.showMessageDialog(jPanel1, "Xác nhận lại mật khẩu sai");
            } else if(JOptionPane.showConfirmDialog(this, "Xác nhận đổi mật khẩu?") == JOptionPane.OK_OPTION) {
                tk.setMk(newPass);
                if (new TaiKhoanDAO().update(tk)) {
                    JOptionPane.showMessageDialog(jPanel1, "Đổi mật khẩu thành công\nVui lòng đăng nhập lại");
                    this.dispose();
                    mf.logout();
                } else {
                    JOptionPane.showMessageDialog(jPanel1, "Đổi mật khẩu thất bại");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpfMatKhauMoi = new javax.swing.JPasswordField();
        jpfMatKhauHienTai = new javax.swing.JPasswordField();
        jpfXacNhanLai = new javax.swing.JPasswordField();
        jbtnDoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Mật khẩu hiện tại:");

        jLabel2.setText("Mật khẩu mới:");

        jLabel3.setText("Xác nhận lại mật khẩu:");

        jbtnDoi.setBackground(new java.awt.Color(204, 204, 255));
        jbtnDoi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnDoi.setText("Đổi");
        jbtnDoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpfMatKhauMoi)
                    .addComponent(jpfMatKhauHienTai)
                    .addComponent(jpfXacNhanLai, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jbtnDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jpfMatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpfMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfXacNhanLai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoiActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_jbtnDoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDoi;
    private javax.swing.JPasswordField jpfMatKhauHienTai;
    private javax.swing.JPasswordField jpfMatKhauMoi;
    private javax.swing.JPasswordField jpfXacNhanLai;
    // End of variables declaration//GEN-END:variables
}
